<a href="https://colab.research.google.com/github/quoctrungsz27/week8_AI/blob/main/Perceptron_Crabs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
url = '/content/crabs.csv'
data = pd.read_csv(url)

# speies B -> 0   O -> 1
# sex M -> 1   F -> 0

In [2]:

from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

# Chuyen du lieu
dataReplace = data.replace(to_replace=["B","O","M","F"],value = [0,1,1,0])
data_x = dataReplace.drop(['sex'], axis=1)
data_y = dataReplace.drop(['speies','index','fontallip','rearwidth',
                           'length','width','depth'], axis=1)
# Du lieu dau vao
X = data_x.to_numpy()
y = data_y.to_numpy()
print(X)
#print(y)

[[ 0.   1.   8.1 ... 16.1 19.   7. ]
 [ 0.   2.   8.8 ... 18.1 20.8  7.4]
 [ 0.   3.   9.2 ... 19.  22.4  7.7]
 ...
 [ 1.  48.  21.9 ... 42.6 47.4 19.5]
 [ 1.  49.  22.5 ... 43.  48.7 19.8]
 [ 1.  50.  23.1 ... 46.2 52.5 21.1]]


In [3]:

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(X_train)   #hoc ti le
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
print(X_train_std[:5],X_train[:5])
print(y.T[:10])
     

[[-1.04381619  0.40142121  0.12996186  0.18595302  0.49604484  0.61536192
   0.34748942]
 [-1.04381619 -0.5569047  -1.07346447 -0.81237881 -1.09400852 -0.98790728
  -1.09198971]
 [ 0.95802308 -0.07774174  0.15861486 -0.46680241 -0.11765996 -0.32405363
   0.0830953 ]
 [ 0.95802308 -0.2830973  -0.09926221 -0.6587893  -0.31292967 -0.39920687
  -0.21067596]
 [ 0.95802308 -1.30987505 -0.50040431 -0.00603387 -0.50819938 -0.54951336
  -0.44569296]] [[ 0.  32.  16.2 13.3 36.  41.7 15.4]
 [ 0.  18.  12.  10.7 24.6 28.9 10.5]
 [ 1.  25.  16.3 11.6 31.6 34.2 14.5]
 [ 1.  22.  15.4 11.1 30.2 33.6 13.5]
 [ 1.   7.  14.  12.8 28.8 32.4 12.7]]
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [4]:
model = Perceptron(max_iter=500, eta0=0.1, random_state = 0) # epoch , toc do hoc 0 - 1 , trang thai lay giai tri ngau nhien
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
#print(y_test)
print('Do chinh xac cua mo hinh:',accuracy_score(y_test,y_pred))

[1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0
 1 0 0 1 0 1 1 0 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0]
Do chinh xac cua mo hinh: 0.9666666666666667


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
